# Use container-based environment for quicker initialization
sudo: false

# Specify the build matrix
language: python
python:
    - '2.7'
env:
    matrix:
        - TEST_SUITE=static

# Add dependency directories to the Travis cache
cache:
    directories:
        - $HOME/.cache/pip

# Delegate the installation step to the custom Travis installation script
install: ./.travis.install.sh

# Delegate the build step to the custom Travis build script
script: ./.travis.build.sh
